# Name: Sophie Spiliotopoulos
# Python Version: Python 2.7 
# Description: Lab 1, a script to clip the floodzones within the basin.shp, and then selecting the part of that clipped floodzone that is within the Special Flood Hazard Area. 

# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# flooding.py
# Created on: 2020-10-16 11:04:22.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: A script exported from the Model Builder in ArcMap. Clips the floodzone file based on the basin,
# then selects the part of the floodzone within the Special Flood Hazard Area
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
floodzones = "floodzones"
basin = "basin"
flood_Clip_shp = "E:\\Comp Programming for GIS\\Data_Lab_1_Geoprocessing_ArcGIS\\flood_Clip.shp"
flooding_shp = "E:\\Comp Programming for GIS\\Data_Lab_1_Geoprocessing_ArcGIS\\flooding.shp"

# Process: Clip
arcpy.Clip_analysis(floodzones, basin, flood_Clip_shp, "")

# Process: Select
arcpy.Select_analysis(flood_Clip_shp, flooding_shp, "\"SFHA\" =  'IN'")

